version: '3.8'

networks:
  default:
    name: zoo
    external: true

services:
  pipeline-confluent-kafka-rest:
    hostname: pipeline-confluent-kafka-rest
    image: pipeline-confluent-kafka-rest
    restart: always
    ports:
      - 8082:8082

